"""
Django settings for drm project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import date

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fauai@0js&9=%@6p8ls!znjsntk6aj)vqem5%_^1b4#^@jp@1y'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'alsafi_drm',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'drm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "alsafi_drm" / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'drm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# LDAP/AD — авторизация (services.ldap) и получение username
LDAP_SERVER = os.environ.get("LDAP_SERVER", "ldap://10.10.2.5")
LDAP_BASE_DN = os.environ.get("LDAP_BASE_DN", "DC=alsafibank,DC=com")
LDAP_DOMAIN = os.environ.get("LDAP_DOMAIN", "alsafibank")  # для формата DOMAIN\username
LDAP_BIND_DN = os.environ.get("LDAP_BIND_DN", "")
LDAP_BIND_USER = os.environ.get("LDAP_BIND_USER", "")
LDAP_BIND_PASSWORD = os.environ.get("LDAP_BIND_PASSWORD", "")

# SSO: пользователь уже в Windows, проверяем по списку допущенных
# Список логинов AD (sAMAccountName), через запятую или в .env: ALLOWED_LDAP_USERNAMES=r.kumash,a.abdullanova
ALLOWED_LDAP_USERNAMES = os.environ.get("ALLOWED_LDAP_USERNAMES", "r.kumash").strip().split(",")
ALLOWED_LDAP_USERNAMES = [u.strip() for u in ALLOWED_LDAP_USERNAMES if u.strip()]

# Только для разработки: подставить пользователя, если REMOTE_USER нет (нет IIS)
SSO_DEV_USER = os.environ.get("SSO_DEV_USER", "")  # например SSO_DEV_USER=r.kumash

# Вход по форме: проверка логина/пароля через services.ldap.verify_user
AUTHENTICATION_BACKENDS = ["alsafi_drm.backends.LDAPBackend"]
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/accounts/login/"


today = date.today().strftime("%d.%m.%Y")
CORR_ACCOUNTS_URL = os.environ.get("CORR_ACCOUNTS_URL", f"https://prod-cbs.alsafibank.com/api/executor-service/reports/data?dateReport={today}&code=ASSETS_LIQUIDITY")
CORR_ACCOUNTS_LOGIN = os.environ.get("CORR_ACCOUNTS_LOGIN", "r.kumash")
CORR_ACCOUNTS_PASSWORD = os.environ.get("CORR_ACCOUNTS_PASSWORD", "Zikolay2018")

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": BASE_DIR / "cache",
    }
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "loggers": {
        "alsafi_drm.backends": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}